# Generated by Django 3.2.3 on 2022-07-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.TextField(max_length=8)),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=30)),
            ],
        ),
    ]
